<a href="https://colab.research.google.com/github/bibilka/Big-Data-processing-technologies/blob/main/laba3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount ("/content/drive")

Mounted at /content/drive


In [3]:
pd.options.display.max_rows = 10

In [8]:
sp500 = pd.read_csv(
  filepath_or_buffer = "/content/drive/MyDrive/sp500.csv", 
  sep=",",
  index_col = 'Symbol',
  usecols=['Symbol','Sector','Price','Book Value']
)
sp500.head()

Sector   Price  Book Value
Symbol                                            
MMM                Industrials  141.14      26.668
ABT                Health Care   39.60      15.573
ABBV               Health Care   53.95       2.954
ACN     Information Technology   79.79       8.326
ACE                 Financials  102.91      86.897

In [6]:
omh = pd.read_csv(
  filepath_or_buffer = "/content/drive/MyDrive/omh.csv", 
  parse_dates=["Date"]
)
omh.set_index('Date', inplace=True)
omh.head()

MSFT    AAPL
Date                     
2014-12-01  48.62  115.07
2014-12-02  48.46  114.63
2014-12-03  48.08  115.93
2014-12-04  48.84  115.49
2014-12-05  48.42  115.00

In [9]:
sp500.describe()

Price     Book Value
count   500.00000     499.000000
mean     77.36860     301.611301
std      87.59694    6195.727862
min       0.00000     -51.275000
25%      38.74500      10.836500
50%      58.35500      19.098000
75%      86.68000      31.386500
max    1197.12000  138425.453100

In [10]:
sp500.Price.describe()

count     500.00000
mean       77.36860
std        87.59694
min         0.00000
25%        38.74500
50%        58.35500
75%        86.68000
max      1197.12000
Name: Price, dtype: float64

In [11]:
sp500.Sector.describe()

count                        500
unique                        13
top       Consumer Discretionary
freq                          85
Name: Sector, dtype: object

In [12]:
sp500.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, MMM to ZTS
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Sector      500 non-null    object 
 1   Price       500 non-null    float64
 2   Book Value  499 non-null    float64
dtypes: float64(2), object(1)
memory usage: 31.8+ KB


In [13]:
sp500.Sector.value_counts()

Consumer Discretionary         85
Financials                     82
Industrials                    64
Information Technology         64
Health Care                    54
                               ..
Materials                      29
Telecommunications Services     6
Consumer Staples                1
Industries                      1
Consumer Discretionary          1
Name: Sector, Length: 13, dtype: int64

In [14]:
np.random.seed(123)
df = pd.DataFrame(np.random.randn(5, 4),columns=['A','B','C','D'])
df

A         B         C         D
0 -1.085631  0.997345  0.282978 -1.506295
1 -0.578600  1.651437 -2.426679 -0.428913
2  1.265936 -0.866740 -0.678886 -0.094709
3  1.491390 -0.638902 -0.443982 -0.434351
4  2.205930  2.186786  1.004054  0.386186

In [15]:
abs(df*2)

A         B         C         D
0  2.171261  1.994691  0.565957  3.012589
1  1.157201  3.302873  4.853358  0.857825
2  2.531873  1.733481  1.357772  0.189418
3  2.982779  1.277804  0.887964  0.868703
4  4.411860  4.373572  2.008108  0.772373

In [16]:
df.iloc[0]


A   -1.085631
B    0.997345
C    0.282978
D   -1.506295
Name: 0, dtype: float64

In [17]:
df = df.iloc[0]

In [19]:
df.iloc[0] - df

A    0.000000
B   -2.082976
C   -1.368609
D    0.420664
Name: 0, dtype: float64

In [20]:
df

A   -1.085631
B    0.997345
C    0.282978
D   -1.506295
Name: 0, dtype: float64

In [24]:
subframe = df[1:4][['B', 'C']].copy()
subframe

B    0.997345
C    0.282978
Name: 0, dtype: float64

In [25]:
df = subframe

Преобразование данных.
Дискретизация и квантилизация

In [27]:
np.random.seed(123456)
dist = np.random.normal(size=10000)
dist

array([ 0.4691123 , -0.28286334, -1.5090585 , ...,  0.26296448,
       -0.83377412, -0.10418135])

In [28]:
bins = pd.cut(dist, 5)
bins

[(-0.633, 0.81], (-0.633, 0.81], (-2.077, -0.633], (-2.077, -0.633], (0.81, 2.254], ..., (-2.077, -0.633], (-0.633, 0.81], (-0.633, 0.81], (-2.077, -0.633], (-0.633, 0.81]]
Length: 10000
Categories (5, interval[float64, right]): [(-3.528, -2.077] < (-2.077, -0.633] < (-0.633, 0.81] <
                                           (0.81, 2.254] < (2.254, 3.698]]

In [29]:
bins.categories

IntervalIndex([(-3.528, -2.077], (-2.077, -0.633], (-0.633, 0.81], (0.81, 2.254], (2.254, 3.698]], dtype='interval[float64, right]')

In [30]:
[q.right - q.left for q in bins.categories]

[1.451, 1.444, 1.443, 1.444, 1.444]

In [31]:
np.random.seed(242)
ages = np.random.randint(6, 70, 50)
ages

array([20, 45,  8, 28, 53,  7, 12, 19, 66, 42, 10, 37, 34, 25, 44, 69, 34,
       67, 25, 51,  8, 50, 33, 42, 20, 31, 64, 51, 59, 11, 40, 32, 33, 29,
       28, 18, 16, 47, 45, 66, 43, 65, 16, 17, 69,  9, 19, 42, 33, 39])

In [32]:
ranges = [6, 12, 18, 35, 50, 70]
labels = ['Youth', 'Young Adult', 'Adult', 'Middle Aged', 'Retired persons']
agebins = pd.cut(ages, ranges, labels=labels)
agebins.describe()

counts  freqs
categories                    
Youth                 7   0.14
Young Adult           4   0.08
Adult                16   0.32
Middle Aged          12   0.24
Retired persons      11   0.22

In [34]:
qbin = pd.qcut(dist, 5)
qbin.describe()

counts  freqs
categories                     
(-3.522, -0.861]    2000    0.2
(-0.861, -0.241]    2000    0.2
(-0.241, 0.261]     2000    0.2
(0.261, 0.866]      2000    0.2
(0.866, 3.698]      2000    0.2

In [35]:
sp500_copy = sp500.copy()
sp500_copy['Price_Group'], bins = pd.qcut(
    sp500_copy.Price,
    5,
    labels=['group_'+str(i) for i in range(1,6)],
    retbins=True
)
sp500_copy.Price_Group

Symbol
MMM     group_5
ABT     group_2
ABBV    group_3
ACN     group_4
ACE     group_5
         ...   
YHOO    group_2
YUM     group_4
ZMH     group_5
ZION    group_1
ZTS     group_1
Name: Price_Group, Length: 500, dtype: category
Categories (5, object): ['group_1' < 'group_2' < 'group_3' < 'group_4' < 'group_5']

In [36]:
bins

array([   0.   ,   34.558,   50.732,   69.586,   97.032, 1197.12 ])

In [37]:
sp500_copy.Price_Group.value_counts()

group_1    100
group_2    100
group_3    100
group_4    100
group_5    100
Name: Price_Group, dtype: int64

Кумулятивные суммы

In [ ]:
pd.Series([1,2,3,4]).cumsum()

In [38]:
pd.Series([1,2,3,4]).cumprod()

0     1
1     2
2     6
3    24
dtype: int64

ранжирование

In [39]:
s = pd.Series([160, 165, 165, 170, 175], index=list('abcde'))
s.rank()

a    1.0
b    2.5
c    2.5
d    4.0
e    5.0
dtype: float64

Относительное изменение

In [40]:
omh[['MSFT']].head()

MSFT
Date             
2014-12-01  48.62
2014-12-02  48.46
2014-12-03  48.08
2014-12-04  48.84
2014-12-05  48.42

In [41]:
omh[['MSFT']].pct_change().head()

MSFT
Date                
2014-12-01       NaN
2014-12-02 -0.003291
2014-12-03 -0.007842
2014-12-04  0.015807
2014-12-05 -0.008600

In [42]:
(48.46 - 48.62)/48.62

-0.003290826820238515

оконные функции

In [44]:
r = omh.MSFT.rolling(3)

In [45]:
r.mean()

Date
2014-12-01          NaN
2014-12-02          NaN
2014-12-03    48.386667
2014-12-04    48.460000
2014-12-05    48.446667
                ...    
2014-12-24    48.190000
2014-12-26    48.156667
2014-12-29    47.823333
2014-12-30    47.450000
2014-12-31    46.973333
Name: MSFT, Length: 22, dtype: float64

In [46]:
omh.MSFT.loc['2014-12-01':'2014-12-03'].mean()

48.38666666666666

In [47]:
omh.MSFT.loc['2014-12-02':'2014-12-04'].mean()

48.46